from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .video_loader_pw import NODE_CLASS_MAPPINGS as VIDEO_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_LOADER_DISPLAY
from .video_info_pw import NODE_CLASS_MAPPINGS as VIDEO_INFO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_INFO_DISPLAY
from .audio_loader_pw import AudioLoaderPW
from .ImageLoaderPW import NODE_CLASSES as IMAGE_LOADER_PW_CLASSES

NODE_CLASS_MAPPINGS.update(VIDEO_LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_INFO_MAPPINGS)
NODE_CLASS_MAPPINGS["Audio Loader PW"] = AudioLoaderPW

NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_LOADER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_INFO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS["Audio Loader PW"] = "Audio Loader PW"

NODE_CLASSES = []
NODE_CLASSES.extend(IMAGE_LOADER_PW_CLASSES)

WEB_DIRECTORY = "./web"

__all__ = [
    "NODE_CLASS_MAPPINGS", 
    "NODE_DISPLAY_NAME_MAPPINGS", 
    "NODE_CLASSES",
    "WEB_DIRECTORY"
]
