from .bool_group_switch import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .group_switch_adv import NODE_CLASS_MAPPINGS as GSA_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GSA_NAME_MAPPINGS

from .video_loader_pw import NODE_CLASS_MAPPINGS as VIDEO_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_LOADER_DISPLAY
from .video_info_pw import NODE_CLASS_MAPPINGS as VIDEO_INFO_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_INFO_DISPLAY
from .video_splitter_pw import NODE_CLASS_MAPPINGS as VIDEO_SPLITTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_SPLITTER_DISPLAY
from .remove_video_from_end import RemoveVideoFromEndPW

from .audio_loader_pw import AudioLoaderPW
from .audio_detector_pw import NODE_CLASS_MAPPINGS as AUDIO_DETECTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as AUDIO_DETECTOR_DISPLAY

from .ImageLoaderPW import NODE_CLASS_MAPPINGS as IMAGE_LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_LOADER_DISPLAY


# ==========================================
# V1 传统节点注册
# ==========================================
NODE_CLASS_MAPPINGS.update(GSA_CLASS_MAPPINGS)

NODE_CLASS_MAPPINGS.update(VIDEO_LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_INFO_MAPPINGS)
NODE_CLASS_MAPPINGS.update(VIDEO_SPLITTER_MAPPINGS)
NODE_CLASS_MAPPINGS["RemoveVideoFromEndPW"] = RemoveVideoFromEndPW

NODE_CLASS_MAPPINGS["Audio Loader PW"] = AudioLoaderPW
NODE_CLASS_MAPPINGS.update(AUDIO_DETECTOR_MAPPINGS) 

NODE_CLASS_MAPPINGS.update(IMAGE_LOADER_MAPPINGS)

# 注册显示名称
NODE_DISPLAY_NAME_MAPPINGS.update(GSA_NAME_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_LOADER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_INFO_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS.update(VIDEO_SPLITTER_DISPLAY)
NODE_DISPLAY_NAME_MAPPINGS["RemoveVideoFromEndPW"] = "Remove Video from End PW"

NODE_DISPLAY_NAME_MAPPINGS["Audio Loader PW"] = "Audio Loader PW"
NODE_DISPLAY_NAME_MAPPINGS.update(AUDIO_DETECTOR_DISPLAY) 

NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_LOADER_DISPLAY)

# ==========================================
# 前端 Web 目录配置
# ==========================================
WEB_DIRECTORY = "./web"

# ==========================================
# 模块导出列表
# ==========================================
__all__ = [
    "NODE_CLASS_MAPPINGS", 
    "NODE_DISPLAY_NAME_MAPPINGS", 
    "WEB_DIRECTORY"
]
